<script type="text/javascript" src="{{asset("/assets/home/js/jquery.min.js")}}"></script>
<script type="text/javascript" src="{{asset("/assets/home/js/bootstrap.min.js")}}"></script>
<script type="text/javascript" src="{{asset("/assets/home/plugins/owl-carousel/owl.carousel.min.js")}}"></script>
<script type="text/javascript" src="{{asset("/assets/home/js/jquery.counterup.min.js")}}"></script>
<script type="text/javascript" src="{{asset("/assets/home/js/waypoints.min.js")}}"></script>
<script type="text/javascript" src="{{asset("/assets/home/plugins/FlexSlider/jquery.flexslider-min.js")}}"></script>
<script type="text/javascript" src="{{asset("/assets/home/js/jquery.magnific-popup.min.js")}}"></script>
<script type="text/javascript" src="{{asset("/assets/home/js/magnific-popup.min.js")}}"></script>
<script type="text/javascript" src="{{asset("/assets/home/js/jquery.cubeportfolio.min.js")}}"></script>
<script type="text/javascript" src="{{asset("/assets/home/js/cubeportfolio/portfolio-masonry-4col.js")}}"></script>
<script type="text/javascript" src="{{asset("/assets/home/js/cubeportfolio/testimonials.js")}}"></script>
<script type="text/javascript" src="{{asset("/assets/home/js/cubeportfolio/team.js")}}"></script>
<script type="text/javascript" src="{{asset("/assets/home/js/cubeportfolio/blog-grid-3col.js")}}"></script>
<script type="text/javascript" src="{{asset("/assets/home/js/custom.js")}}"></script>
<script type="text/javascript" src="{{asset("/assets/plugins/validate/Validform_v5.3.2_min.js")}}"></script>
<script type="text/javascript" src="{{asset("/assets/plugins/layer/layer.js")}}"></script>
<script type="text/javascript" src="{{asset("/assets/plugins/weui/lrz.min.js")}}"></script>
<script type="text/javascript" src="{{asset("/assets/home/js/app.js")}}"></script>

